wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: huggingface
    huggingface_version: 4.14.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1652114373
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 2
      4: 3.7.11
      5: 0.12.14
      6: 4.14.1
      8:
      - 5
no_repeat_ngram_size:
  desc: null
  value: 3
num_beams:
  desc: null
  value: 1
repetition_penalty:
  desc: null
  value: 0.8518749113595381
temperature:
  desc: null
  value: 1.3655821316862622
